name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liMWN5c9lKFRgg4n"
GITHUB_OWNER = "Versior"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://daohang.20000424.xyz/"
NEXT_PUBLIC_API_URL="https://daohang.20000424.xyz/"

